name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build (Server)
        run: |
          npm ci
          npm run build
        working-directory: ./mime-game-server

      - name: Install dependencies and build (Client)
        run: |
          npm ci
          npm run build
        working-directory: ./mime-game-client

      - name: Make deploy.sh executable
        run: chmod +x ./deploy.sh

      - name: Check important files before SCP
        run: |
          echo "== Checking deploy.sh =="
          ls -al ./deploy.sh || echo "Missing deploy.sh"

          echo "== Server build output =="
          ls -al ./mime-game-server/dist || echo "Missing server dist"

          echo "== Client build output =="
          ls -al ./mime-game-client/.next || echo "Missing client .next"

      - name: Print full workspace structure
        run: |
          echo "== Full file tree =="
          ls -alR

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./deploy.sh ./mime-game-server/dist/ ./mime-game-client/.next/"
          target: "/home/ubuntu/mime-game"
          strip_components: 0
          overwrite: true
          debug: true
          port: 22
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          tar_dereference: false
          tar_exec: tar

      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/mime-game
            chmod +x ./deploy.sh
            ./deploy.sh